[option]
exclude_paths = []
textwidth = 80
copyright_linenum = 1
copyright_year = "2024"
copyright_holder = "veznitom"
indent = 4
prefix_inout = "io_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "Intf"
re_required_assert = "^[a-z]+[a-z0-9_]*$"
re_required_assert_property = "^[a-z]+[a-z0-9_]*$"
re_required_checker = "^[a-z]+[a-z0-9_]*$"
re_required_class = "^[a-z]+[a-z0-9_]*$"
re_required_function = "^[a-z]+[a-z0-9_]*$"
re_required_generateblock = "^[a-z]+[a-z0-9_]*$"
re_required_genvar = "^[a-z]+[a-z0-9_]*$"
re_required_instance = "^[a-z]+[a-z0-9_]*$"
re_required_interface = "^f_[a-z]+[a-z0-9_]*$"
re_required_localparam = "^[A-Z]+[A-Z0-9_]*$"
re_required_modport = "^[a-z]+[a-z0-9_]*$"
re_required_module_ansi = "^[a-z]+[a-zA-Z0-9_]*$"
re_required_module_nonansi = "^[A-Z]+[A-Z0-9_]*$"
re_required_package = "^[a-z]+[a-z0-9_]*$"
re_required_parameter = "^[A-Z]+[A-Z0-9_]*$"
re_required_port_inout = "^[a-z]+[a-z0-9_]*$"
re_required_port_input = "^[a-z]+[a-z0-9_]*$"
re_required_port_output = "^[a-z]+[a-z0-9_]*$"
re_required_port_ref = "^[a-z]+[a-z0-9_]*$"
re_required_port_interface = "^[a-z]+[a-z0-9_]*$"
re_required_program = "^[a-z]+[a-z0-9_]*$"
re_required_property = "^[a-z]+[a-z0-9_]*$"
re_required_sequence = "^[a-z]+[a-z0-9_]*$"
re_required_task = "^[a-z]+[a-z0-9_]*$"
re_required_var_class = "^[a-z]+[a-z0-9_]*$"
re_required_var_classmethod = "^[a-z]+[a-z0-9_]*$"
re_forbidden_assert = ".*"
re_forbidden_assert_property = ".*"
re_forbidden_checker = ".*"
re_forbidden_class = ".*"
re_forbidden_function = ".*"
re_forbidden_generateblock = ".*"
re_forbidden_genvar = ".*"
re_forbidden_instance = ".*"
re_forbidden_interface = ".*"
re_forbidden_localparam = ".*"
re_forbidden_modport = ".*"
re_forbidden_module_ansi = ".*"
re_forbidden_module_nonansi = ".*"
re_forbidden_package = ".*"
re_forbidden_parameter = ".*"
re_forbidden_port_inout = ".*"
re_forbidden_port_input = ".*"
re_forbidden_port_output = ".*"
re_forbidden_port_ref = ".*"
re_forbidden_port_interface = ".*"
re_forbidden_program = ".*"
re_forbidden_property = ".*"
re_forbidden_sequence = ".*"
re_forbidden_task = ".*"
re_forbidden_var_class = ".*"
re_forbidden_var_classmethod = ".*"

[textrules]
header_copyright = true
style_directives = true
style_semicolon = true
style_textwidth = true

[syntaxrules]
action_block_with_side_effect = true
blocking_assignment_in_always_at_edge = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = true
enum_with_type = true
eventlist_comma_always_ff = true
eventlist_or = false
explicit_case_default = true
explicit_if_else = false
function_same_as_system_function = false
function_with_automatic = true
general_always_level_sensitive = true
general_always_no_edge = true
generate_case_with_label = false
generate_for_with_label = false
generate_if_with_label = false
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
inout_with_tri = false
input_with_var = false
interface_port_with_modport = true
keyword_forbidden_always = true
keyword_forbidden_always_comb = false
keyword_forbidden_always_ff = false
keyword_forbidden_always_latch = false
keyword_forbidden_generate = false
keyword_forbidden_logic = false
keyword_forbidden_priority = false
keyword_forbidden_unique = false
keyword_forbidden_unique0 = false
keyword_forbidden_wire_reg = false
keyword_required_generate = true
localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = false
loop_statement_in_always_ff = false
loop_statement_in_always_latch = false
loop_variable_declaration = true
lowercamelcase_interface = false
lowercamelcase_module = false
lowercamelcase_package = false
module_ansi_forbidden = false
module_nonansi_forbidden = false
multiline_for_begin = true
multiline_if_begin = true
non_blocking_assignment_in_always_comb = true
non_blocking_assignment_in_always_no_edge = true
operator_case_equality = true
operator_incdec = false
operator_self_assignment = false
output_with_var = false
package_item_not_in_package = false
parameter_default_value = true
parameter_explicit_type = true
parameter_in_generate = true
parameter_in_package = true
parameter_type_twostate = true
prefix_inout = true
prefix_input = true
prefix_instance = true
prefix_interface = true
prefix_module = false
prefix_output = true
prefix_package = true
procedural_continuous_assignment = true
re_forbidden_assert = false
re_forbidden_assert_property = false
re_forbidden_checker = false
re_forbidden_class = false
re_forbidden_function = false
re_forbidden_generateblock = false
re_forbidden_genvar = false
re_forbidden_instance = false
re_forbidden_interface = false
re_forbidden_localparam = false
re_forbidden_modport = false
re_forbidden_module_ansi = false
re_forbidden_module_nonansi = false
re_forbidden_package = false
re_forbidden_parameter = false
re_forbidden_port_inout = false
re_forbidden_port_input = false
re_forbidden_port_interface = false
re_forbidden_port_output = false
re_forbidden_port_ref = false
re_forbidden_program = false
re_forbidden_property = false
re_forbidden_sequence = false
re_forbidden_task = false
re_forbidden_var_class = false
re_forbidden_var_classmethod = false
re_required_assert = false
re_required_assert_property = false
re_required_checker = false
re_required_class = false
re_required_function = false
re_required_generateblock = false
re_required_genvar = false
re_required_instance = false
re_required_interface = false
re_required_localparam = false
re_required_modport = false
re_required_module_ansi = false
re_required_module_nonansi = true
re_required_package = false
re_required_parameter = false
re_required_port_inout = false
re_required_port_input = false
re_required_port_interface = false
re_required_port_output = false
re_required_port_ref = false
re_required_program = false
re_required_property = false
re_required_sequence = false
re_required_task = false
re_required_var_class = false
re_required_var_classmethod = false
sequential_block_in_always_comb = false
sequential_block_in_always_ff = false
sequential_block_in_always_latch = false
style_commaleading = false
style_indent = true
style_keyword_0or1space = true
style_keyword_0space = false
style_keyword_1or2space = false
style_keyword_1space = false
style_keyword_construct = false
style_keyword_datatype = false
style_keyword_end = false
style_keyword_maybelabel = false
style_keyword_new = true
style_keyword_newline = false
style_operator_arithmetic = false
style_operator_arithmetic_leading_space = false
style_operator_boolean = false
style_operator_boolean_leading_space = false
style_operator_integer = false
style_operator_integer_leading_space = false
style_operator_unary = false
style_trailingwhitespace = true
tab_character = true
#unpacked_array = true
uppercamelcase_interface = false
uppercamelcase_module = true
uppercamelcase_package = false
